### ISSUE TITLE
R runs with insufficient arguments when using the 'auto-found' executable

### ISSUE THREAD

**Issue by jspaezp** [jdrudolph/PluginInterop#1]
Hello Jan!

I was trying out the new version of the plugin and was able to find out that then running R scripts through the plugin i got this output

![r error](https://user-images.githubusercontent.com/8116459/27006292-3d3d005a-4dfe-11e7-831f-a92d708c8f31.PNG)

This happens (1) when i run the script with the auto-found executable and (2) when I explicitly give an R.exe executable path. Nonetheless it does not happen when I provide an Rscript.exe exetuable in my system\.

Therefore I believe it is running the command as 'R.exe script args ... ' and not as 'Rscript.exe script args'.

This can be further confirmed by the fact that running

```{R}
R --slave catch_perseus_data.R parameters.xml mat1.txt mat2.txt
```

returns

```{R}
ARGUMENT 'catch_perseus_data.R' __ignored__

ARGUMENT 'parameters.xml' __ignored__

ARGUMENT 'mat1.txt' __ignored__

ARGUMENT 'mat2.txt' __ignored__

q()
```

.... whilst 

```{R}
Rscript --slave catch_perseus_data.R parameters.xml mat1.txt mat2.txt
```

does not return an output.

After digging a little bit it might be due to this return statement ... (not 100% sure)

https://github.com/jdrudolph/PluginInterop/blob/ed07daee2086129531243725a597cd322b7e2759/PluginInterop/R/Utils.cs#L21

Let me know what you think,
Best !

**Comment by jdrudolph** [comment]
now the choice of `Rscript` should be consistent

**Comment by jspaezp** [comment]
08819acd87d1c7509993cb8be23b9d0e7a9457a9

Fixed it in my system.

Thanks for the quick work!
